env: dev
logLevel: info
hosts: 
- name: localhost 
  port: 3000
  scheme: weightedroundrobin
  health: /
  interval: 10
  servers:
  - name:  reqres.in
    weight: 5
    health: 
  - name:  reqres.in
    weight: 3
  - name:  reqres.in
    weight: 2
- name: localhost 
  port: 3001
  scheme: weightedroundrobin
  health: /health
  interval: 10
  servers:
  - name: localhost:9081
    weight: 5
    health: 
  - name: localhost:9082
    weight: 3
  - name: localhost:9083
    weight: 2
