env: dev
logLevel: info
port: 3000
host: 
  name: localhost
  scheme: roundrobing
  servers:
  - name: www.google.com
    weight: 5
  - name: 1.1.1.1
    weight: 3
  - name: www.youtube.com
    weight: 2
